require('dotenv').config();
const express=require('express');const cors=require('cors');const path=require('path');const fs=require('fs');const crypto=require('crypto');const jwt=require('jsonwebtoken');const OpenAI=require('openai');
const app=express();const PORT=Number(process.env.PORT||3000);const JWT_SECRET=process.env.JWT_SECRET||'dev-only-change-this-secret';
const DATA_DIR=path.join(__dirname,'data');const USERS_FILE=path.join(DATA_DIR,'users.json');const OFFERS_FILE=path.join(DATA_DIR,'offers.json');fs.mkdirSync(DATA_DIR,{recursive:true});
app.use(cors({origin:process.env.CORS_ORIGIN||true}));app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));
const procurementSlots=[{id:'AC-101',centre:'Pune Central Procurement Centre',date:'2026-09-12',time:'09:00 AM',capacity:80,booked:54,status:'Open'},{id:'AC-102',centre:'Baramati Grain Centre',date:'2026-09-12',time:'11:30 AM',capacity:60,booked:49,status:'Limited'},{id:'AC-103',centre:'Nashik Market Yard',date:'2026-09-13',time:'10:00 AM',capacity:100,booked:31,status:'Open'}];
const crops=[{id:'CR-001',name:'Premium Wheat',category:'Cereals',emoji:'🌾',price:25,quantity:1000,rating:4.8,farmer:'Ramesh Patil',description:'High-quality wheat suitable for flour and food processing.'},{id:'CR-002',name:'Basmati Rice',category:'Cereals',emoji:'🍚',price:48,quantity:800,rating:4.9,farmer:'Sunita Agro FPO',description:'Aromatic long-grain rice from a verified farmer group.'},{id:'CR-003',name:'Maize',category:'Cereals',emoji:'🌽',price:22,quantity:1200,rating:4.7,farmer:'Vijay More',description:'Fresh yellow maize with consistent grain quality.'},{id:'CR-004',name:'Onions',category:'Vegetables',emoji:'🧅',price:18,quantity:2000,rating:4.8,farmer:'Nashik Growers',description:'Firm onions packed for wholesale procurement.'},{id:'CR-005',name:'Tomatoes',category:'Vegetables',emoji:'🍅',price:24,quantity:500,rating:4.8,farmer:'Anita Shinde',description:'Fresh tomatoes harvested for same-week delivery.'},{id:'CR-006',name:'Potatoes',category:'Vegetables',emoji:'🥔',price:20,quantity:1500,rating:4.9,farmer:'Kisan Fresh',description:'Uniform-size potatoes for retail and processing.'},{id:'CR-007',name:'Mangoes',category:'Fruits',emoji:'🥭',price:70,quantity:300,rating:4.9,farmer:'Konkan Farms',description:'Premium seasonal mangoes with careful grading.'},{id:'CR-008',name:'Bananas',category:'Fruits',emoji:'🍌',price:30,quantity:800,rating:4.8,farmer:'Green Valley Farm',description:'Fresh bananas suited for bulk institutional buying.'},{id:'CR-009',name:'Tur Dal',category:'Pulses',emoji:'🫘',price:96,quantity:450,rating:4.7,farmer:'Sahyadri FPO',description:'Cleaned and graded pigeon pea for wholesale buyers.'},{id:'CR-010',name:'Chickpeas',category:'Pulses',emoji:'🫛',price:82,quantity:600,rating:4.8,farmer:'Matoshree Farms',description:'High-quality chickpeas with good shelf stability.'}];
function readJson(file){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return[]}}function writeJson(file,data){fs.writeFileSync(file,JSON.stringify(data,null,2))}
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){return `${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`}function verifyPassword(password,stored){const [salt,key]=String(stored).split(':');if(!salt||!key)return false;const actual=crypto.scryptSync(password,salt,64);return crypto.timingSafeEqual(actual,Buffer.from(key,'hex'))}
function auth(req,res,next){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return res.status(401).json({success:false,message:'Authentication required.'});try{req.user=jwt.verify(token,JWT_SECRET);next()}catch{return res.status(401).json({success:false,message:'Invalid or expired session.'})}}
app.get('/api/health',(_req,res)=>res.json({ok:true,service:'AgriConnect API',time:new Date().toISOString(),aiConfigured:Boolean(process.env.OPENAI_API_KEY)}));
app.post('/api/auth/register',(req,res)=>{const {name,email,password,role='farmer'}=req.body||{};if(!name||!email||!password||!['farmer','buyer'].includes(role))return res.status(400).json({success:false,message:'Name, email, password and a valid role are required.'});if(String(password).length<6)return res.status(400).json({success:false,message:'Password must be at least 6 characters.'});const users=readJson(USERS_FILE);const normalized=String(email).trim().toLowerCase();if(users.some(u=>u.email===normalized))return res.status(409).json({success:false,message:'An account with this email already exists.'});const user={id:`USR-${Date.now()}`,name:String(name).trim().slice(0,100),email:normalized,role,passwordHash:hashPassword(String(password)),createdAt:new Date().toISOString()};users.push(user);writeJson(USERS_FILE,users);const token=jwt.sign({sub:user.id,name:user.name,email:user.email,role:user.role},JWT_SECRET,{expiresIn:'7d'});res.status(201).json({success:true,token,user:{id:user.id,name:user.name,email:user.email,role:user.role}})});
app.post('/api/auth/login',(req,res)=>{const {email,password}=req.body||{};const user=readJson(USERS_FILE).find(u=>u.email===String(email||'').trim().toLowerCase());if(!user||!verifyPassword(String(password||''),user.passwordHash))return res.status(401).json({success:false,message:'Invalid email or password.'});const token=jwt.sign({sub:user.id,name:user.name,email:user.email,role:user.role},JWT_SECRET,{expiresIn:'7d'});res.json({success:true,token,user:{id:user.id,name:user.name,email:user.email,role:user.role}})});
app.get('/api/auth/me',auth,(req,res)=>res.json({success:true,user:req.user}));
app.get('/api/procurement/slots',(_req,res)=>res.json({success:true,data:procurementSlots}));
app.post('/api/procurement/book',auth,(req,res)=>{const {crop,quantity,slotId}=req.body||{};const qty=Number(quantity);const slot=procurementSlots.find(x=>x.id===slotId);if(!crop||!Number.isFinite(qty)||qty<=0||qty>100000||!slot)return res.status(400).json({success:false,message:'Valid crop, quantity and slot are required.'});if(slot.booked>=slot.capacity)return res.status(409).json({success:false,message:'This slot is full.'});slot.booked++;res.status(201).json({success:true,booking:{bookingId:`AGR-${Date.now()}`,farmerName:req.user.name,crop:String(crop).slice(0,80),quantity:qty,slotId,centre:slot.centre,date:slot.date,time:slot.time,status:'Confirmed'}})});
app.get('/api/crops',(req,res)=>{const q=String(req.query.q||'').toLowerCase();const category=String(req.query.category||'').toLowerCase();const result=crops.filter(c=>(!q||`${c.name} ${c.description} ${c.farmer}`.toLowerCase().includes(q))&&(!category||c.category.toLowerCase()===category));res.json({success:true,data:result})});
app.get('/api/offers',auth,(req,res)=>res.json({success:true,data:readJson(OFFERS_FILE).filter(o=>o.buyerId===req.user.sub)}));
app.post('/api/offers',auth,(req,res)=>{const {cropId,quantity,offerPrice,note}=req.body||{};const crop=crops.find(x=>x.id===cropId);const qty=Number(quantity),price=Number(offerPrice);if(!crop||!Number.isFinite(qty)||qty<=0||qty>crop.quantity||!Number.isFinite(price)||price<=0)return res.status(400).json({success:false,message:'Enter a valid crop, quantity and offer price within available stock.'});const offers=readJson(OFFERS_FILE);const offer={id:`OFF-${Date.now()}`,cropId,cropName:crop.name,quantity:qty,offerPrice:price,note:String(note||'').slice(0,500),buyerId:req.user.sub,buyerName:req.user.name,status:'pending',createdAt:new Date().toISOString()};offers.push(offer);writeJson(OFFERS_FILE,offers);res.status(201).json({success:true,offer})});
const aiClient=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
app.post('/api/ai/chat',async(req,res)=>{const message=String(req.body?.message||'').trim();if(!message||message.length>2000)return res.status(400).json({success:false,message:'Message is required and must be under 2000 characters.'});if(!aiClient)return res.json({success:true,mode:'demo',reply:'AI is not configured yet. Add OPENAI_API_KEY to the server environment to enable the live AgriConnect Assistant.'});try{const response=await aiClient.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',instructions:'You are AgriConnect Assistant for Indian farmers and buyers. Give concise practical guidance about procurement scheduling, crop selling, marketplace usage, offers, payments and general agriculture. Do not invent live prices or official government facts; clearly label estimates and advise verification.',input:message});res.json({success:true,mode:'live',reply:response.output_text||'I could not generate a response.'})}catch(error){console.error('OpenAI error:',error);res.status(502).json({success:false,message:'AI provider request failed. Check OPENAI_API_KEY, OPENAI_MODEL and server logs.'})}});
app.use((_req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log(`AgriConnect running on http://localhost:${PORT}`));
